### ISSUE TITLE
scikit-fem is now supported!

### ISSUE THREAD

**Issue by ZAARAOUI999** [ZAARAOUI999/feplot#8]
Example of how to use:

```python
from feplot.pylab import Plotter
from feplot.helpers import SKMesh

pl = Plotter()
# M is the skfem mesh and X is the scalars to plot
pl.add_mesh([SKMesh(M)], [X], label='$x$', show_mesh=True)
pl.hide_grid()
pl.add_axes()
pl.add_annotation(0.7, 0.05, r'$\bf{Example\ 01}$')
```
Some of results:
<img src="https://user-images.githubusercontent.com/115699524/202281037-8515c6b9-d07e-49c9-a283-9f6bab766a6f.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281049-d1a527ec-ceab-482b-8ab0-2bc94896d886.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281055-c0f79770-aa7a-442f-abdd-885b5671f727.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281058-331134d6-ea75-43bb-805b-6125fc9d638d.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281063-36e0d3b2-cefa-471c-af9a-3f84c1d76e3c.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281074-1c117f60-1652-4d89-88da-afb072725c2f.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281079-fd4b46f6-e0da-453c-976c-483d8ce816ea.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281083-b9ee8275-52eb-46d5-b2ed-6a12e1c9acd1.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281087-1d1f0497-7227-4e81-abbf-188761c5c396.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281093-360cedcd-1a01-40b2-91f8-4ebb664a6e08.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281095-5c16b5f6-2cf8-46a7-b5eb-73f3aff970b6.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281109-799851a9-11f7-42cf-86f9-b02e556bb596.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281112-e7f4cb13-01d8-41ea-9bf7-91b0b4d57678.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281115-35d99f95-a54b-48cd-af1e-5b7b022053e1.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281118-621d3b21-1092-4a84-a0fa-da2cb899c544.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281123-ee612d3d-36be-49a4-b21b-3734997cb325.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281132-772bd3f4-f191-4325-9989-1ccb25a04519.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281133-e09d136a-7aaa-4b1b-87d7-80f9e529800c.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281139-20845da3-8f19-40a4-bbbd-42fda91db90a.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281142-27f7ce81-598a-403a-b89f-a85c0a52fc1c.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281151-dbf28845-adc0-47c5-9342-974f2ac07e5c.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281158-494fba71-5c33-4315-8cf9-e079eb23a976.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281163-af727b02-a94f-4d5e-a46f-5e5221848a4a.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281170-18c7c8e0-874c-4724-bf89-79928c6589d2.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281179-0a0c111e-f2ab-48f1-9306-77523c995c4b.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281185-e50ab65b-5506-46da-a3dc-8ad051376672.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281188-8602ffbc-791c-4ef9-8189-6cb25b9e8e8a.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281194-3595a61f-7a5d-4638-b43d-61837b7e52c2.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281202-c95bbf0a-f1f9-4432-8f93-d7eb4b1619bc.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281206-1b4d89bb-4123-4b25-814a-59c06e8706e7.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281208-5364f9c5-609d-4df1-a123-cf61647aa1a6.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281212-8788b78b-d6c8-49db-a495-ebab96f42089.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281219-6bfaa810-2a5f-4754-abd7-1dcf4e268a80.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281223-9e018620-d32e-4739-8e0e-60492e39f9a3.png" width="15%"></img> <img src="https://user-images.githubusercontent.com/115699524/202281228-824ef875-8a60-4908-871e-6a9fb22a75e5.png" width="15%"></img>

**Comment by adtzlr** [comment]
Great! However, what has happened in the visualization of example 11?

**Comment by ZAARAOUI999** [comment]
I taked all of those examples from `scikit-fem` examples folder. In the 11th example they worked on linear elasticity. I taked the u defined by `u = solve(*condense(K, x=u, I=I))` as scalars. But the results didn't seem like a displacement result. It may due to a problem with the projection method defined  in the `volume_plot` code. There are some differences between `FElupe` and `scikit-fem` at the level of the choice of the cell points order. Take a look at this:
```python
hex_mask = np.array([[0, 1, 2, 3], [0, 1, 5, 4],
                     [1, 2, 6, 5], [2, 3, 7, 6],
                     [0, 3, 7, 4], [4, 5, 6, 7]])

hex_mask_sk = np.array([[7, 4, 2, 6], [4, 1, 0, 2],
                        [1, 5, 3, 0], [5, 7, 6, 3],
                        [7, 4, 1, 5], [6, 2, 0, 3]])
```
The first one is how `FElupe` takes faces from a hexahedron cell and the second is for `scikit-fem`. The projection  worked well with `FElupe` but for the second it needs more work.

**Comment by ZAARAOUI999** [comment]
BTW, I'm waiting for the v5.4.0 release 😁. I'm interested in the visco-hyperelastic behavior of non-filled and filled rubbers and I'm glad  to see the Mullins effect there in `FElupe`. Also, It will be a fantastic thing if  an implementation of viscoelastic materials (linear and non linear models) comes there (may be into `matADi`), the unify idea was a great job.
